name: Run Frontend Tests

on: [push, workflow_dispatch, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Restore node_modules cache
        id: nodemodules-cache
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('frontend/yarn.lock') }}

      - name: Install dependencies
        if: steps.nodemodules-cache.outputs.cache-hit != 'true'
        working-directory: frontend
        run: yarn install

      - name: Run tests
        working-directory: frontend
        run: yarn run test
